#!/usr/bin/env python3
# file: generate_guid_index.py
# version: 1.0.0
# guid: 04ecd3e6-9982-436d-880b-dac881144a89
# last-edited: 2026-07-14
"""Build a title/path <-> GUID index from file version headers.

Scans every git-tracked file in a repo, pulls the `file`/`version`/`guid`
fields out of its version header (see falkcorp house standard:
file-headers.md), and writes a machine-readable index plus a
human-readable table. Also flags duplicate GUIDs (copy-pasted headers
that were never re-rolled) and GUIDs that are not valid UUIDs (leftover
placeholder text) — the header standard requires uniqueness but nothing
else enforces it.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

HEADER_LINE_RE = re.compile(
    r"^\s*(?://|#|<!--)\s*(file|version|guid|last-edited):\s*(.+?)\s*(?:-->)?\s*$"
)
UUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
MD_HEADING_RE = re.compile(r"^#\s+(.+?)\s*$")
YAML_NAME_RE = re.compile(r"^name:\s*['\"]?(.+?)['\"]?\s*$")


def tracked_files(repo_root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=repo_root, capture_output=True, text=True, check=True
    ).stdout
    return [repo_root / line for line in out.splitlines() if line]


def parse_header(path: Path) -> dict[str, str] | None:
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()[:20]
    except OSError:
        return None

    fields: dict[str, str] = {}
    for line in lines:
        m = HEADER_LINE_RE.match(line)
        if m:
            fields[m.group(1)] = m.group(2)
    return fields if "guid" in fields else None


def guess_title(path: Path, body: str) -> str:
    if path.suffix == ".md":
        for line in body.splitlines():
            m = MD_HEADING_RE.match(line)
            if m:
                return m.group(1)
    elif path.suffix in (".yml", ".yaml"):
        for line in body.splitlines():
            m = YAML_NAME_RE.match(line)
            if m:
                return m.group(1)
    return path.stem.replace("-", " ").replace("_", " ")


def build_records(repo_root: Path) -> list[dict]:
    records = []
    for path in tracked_files(repo_root):
        fields = parse_header(path)
        if fields is None:
            continue
        try:
            body = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            body = ""
        rel_path = str(path.relative_to(repo_root))
        records.append(
            {
                "path": rel_path,
                "guid": fields["guid"],
                "title": guess_title(path, body),
                "version": fields.get("version", ""),
                "header_path": fields.get("file", ""),
                "path_mismatch": bool(fields.get("file"))
                and fields.get("file") != rel_path,
            }
        )
    records.sort(key=lambda r: r["path"])
    return records


def render_markdown(records: list[dict], duplicates: dict, malformed: list[dict]) -> str:
    lines = [
        "# GUID Index",
        "",
        f"Generated by `generate_guid_index.py` from {len(records)} file headers.",
        "Do not edit by hand — regenerate instead.",
        "",
    ]

    if duplicates:
        lines += [
            "## Duplicate GUIDs",
            "",
            "These GUIDs are shared by more than one file, which breaks the "
            "identify-across-renames guarantee. Re-roll all but one file in each group.",
            "",
        ]
        for guid, paths in sorted(duplicates.items(), key=lambda kv: -len(kv[1])):
            lines.append(f"- `{guid}` ({len(paths)} files)")
            for p in paths:
                lines.append(f"  - {p}")
        lines.append("")

    if malformed:
        lines += [
            "## Malformed GUIDs",
            "",
            "These are not valid UUIDs (likely leftover placeholder text).",
            "",
        ]
        for r in malformed:
            lines.append(f"- `{r['guid']}` — {r['path']}")
        lines.append("")

    lines += ["## Index", "", "| Title | GUID | Path |", "| --- | --- | --- |"]
    for r in sorted(records, key=lambda r: r["title"].lower()):
        lines.append(f"| {r['title']} | `{r['guid']}` | {r['path']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", help="Repo root to scan (default: cwd)")
    parser.add_argument("--json-output", default=".github/guid-index.json")
    parser.add_argument("--md-output", default="docs/guid-index.md")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    json_output = repo_root / args.json_output
    md_output = repo_root / args.md_output

    records = build_records(repo_root)

    by_guid: dict[str, list[str]] = defaultdict(list)
    for r in records:
        by_guid[r["guid"]].append(r["path"])
    duplicates = {g: paths for g, paths in by_guid.items() if len(paths) > 1}
    malformed = [r for r in records if not UUID_RE.match(r["guid"])]

    json_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8")

    md_output.parent.mkdir(parents=True, exist_ok=True)
    md_output.write_text(render_markdown(records, duplicates, malformed), encoding="utf-8")

    print(f"Indexed {len(records)} files with GUID headers.")
    if duplicates:
        dupe_files = sum(len(p) for p in duplicates.values())
        print(
            f"WARNING: {len(duplicates)} GUIDs are duplicated across {dupe_files} files.",
            file=sys.stderr,
        )
    if malformed:
        print(f"WARNING: {len(malformed)} GUIDs are not valid UUIDs.", file=sys.stderr)

    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a", encoding="utf-8") as f:
            f.write(f"duplicate-count={len(duplicates)}\n")
            f.write(f"malformed-count={len(malformed)}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
